# Generated by Django 4.1.2 on 2022-10-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='اسم المستخدم')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطالب/ة')),
                ('graduate_year', models.CharField(max_length=100, verbose_name='سنة التخرج')),
                ('to', models.CharField(max_length=250, verbose_name='الجهة المصدر اليها')),
                ('Dnumber', models.CharField(max_length=20, verbose_name='رقم الوثيقة')),
                ('Ddate', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الوثيقة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Cname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.city', verbose_name='المحافظة')),
                ('Dname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department', verbose_name='القسم')),
            ],
        ),
    ]
