# Generated by Django 4.1.2 on 2022-10-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city_department_studentdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='Cname',
            field=models.CharField(max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='department',
            name='Dname',
            field=models.CharField(max_length=100, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='Ddate',
            field=models.DateField(verbose_name='تاريخ الوثيقة'),
        ),
    ]
