# Generated by Django 4.1.2 on 2022-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_city_cname_alter_department_dname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='Ddate',
            field=models.DateTimeField(verbose_name='تاريخ الوثيقة'),
        ),
    ]
