# Generated by Django 4.1.2 on 2022-10-24 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentdocument_ddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdocument',
            name='Ddate',
        ),
    ]
