# Generated by Django 4.1.2 on 2022-10-24 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_studentdocument_ddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.city', verbose_name='المحافظة')),
                ('Dname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department', verbose_name='القسم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='اسم المستخدم')),
            ],
        ),
    ]
