# Generated by Django 4.1.2 on 2022-10-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
