# Generated by Django 4.1.2 on 2022-10-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_studentdocument_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdocument',
            name='Cname',
            field=models.CharField(max_length=100, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='Dname',
            field=models.CharField(max_length=100, verbose_name='القسم'),
        ),
    ]
