# Generated by Django 4.1.2 on 2022-10-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_studentdocument_cname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='check_post',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
