# Generated by Django 4.1.2 on 2022-11-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_studentdocument_check_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='اسم المستخدم')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطالب/ة')),
                ('Dname', models.CharField(max_length=100, verbose_name='القسم')),
                ('Cname', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('stage', models.CharField(max_length=50, verbose_name='المرحلة')),
                ('state', models.CharField(choices=[('استضافة', 'استضافة'), ('نقل', 'نقل'), ('تأجيل', 'تأجيل'), ('رسوب', 'رسوب'), ('ترقين قيد', 'ترقين قيد')], max_length=100, verbose_name='حالة الطالب')),
                ('year', models.CharField(max_length=50, verbose_name='العام الدراسي')),
                ('note', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'حالات الطلبة',
            },
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'المحافظات'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'الاقسام العلمية'},
        ),
        migrations.AlterModelOptions(
            name='studentdocument',
            options={'verbose_name_plural': 'جدول وثائق الطلبة'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'بروفايل المستخدمين'},
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='check_post',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
