# Generated by Django 4.1.2 on 2022-11-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_studentstatus_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='study',
            field=models.CharField(choices=[('الاولى', 'الاولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة')], max_length=20, null=True, verbose_name='الدراسة'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='stage',
            field=models.CharField(choices=[('الاولى', 'الاولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة')], max_length=50, verbose_name='المرحلة'),
        ),
    ]
