# Generated by Django 4.1.2 on 2022-11-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_studentstatus_study_alter_studentstatus_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='study',
            field=models.CharField(choices=[('الصباحية', 'الصباحية'), ('المسائية', 'المسائية')], max_length=20, null=True, verbose_name='الدراسة'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('get_from', models.CharField(max_length=200, verbose_name='الجهة')),
                ('year', models.CharField(max_length=200, verbose_name='العام الدراسي')),
                ('date', models.DateField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Cname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.city', verbose_name='المحافظة')),
                ('Dname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name_plural': 'التعميم/الاشعارات',
            },
        ),
    ]
