# Generated by Django 4.1.2 on 2022-11-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_notifications_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='client_id',
        ),
    ]
