# Generated by Django 4.1.2 on 2022-11-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_notifications_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasjilDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('study', models.CharField(choices=[('الصباحية', 'الصباحية'), ('المسائية', 'المسائية')], max_length=50, verbose_name='الدراسة')),
                ('year_grad', models.CharField(max_length=50, verbose_name='سنة التخرج')),
                ('to', models.CharField(max_length=300, verbose_name='الجهة/الى')),
                ('docType', models.CharField(choices=[('وثيقة بالدرجات', 'وثيقة بالدرجات'), ('وثيقة بالتسلسل', 'وثيقة بالتسلسل'), ('وثيقة بالمعدل', 'وثيقة بالمعدل')], max_length=50, verbose_name='نوع الوثيقة')),
                ('note', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='TasjilDocument/%y/%m')),
                ('Cname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.city', verbose_name='المحافظة')),
                ('Dname', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name_plural': 'وثائق التسجيل العام',
            },
        ),
    ]
