# Generated by Django 4.1.2 on 2022-11-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tasjildocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='اسم المستخدم')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطالب/ة')),
                ('Dname', models.CharField(max_length=100, verbose_name='القسم')),
                ('Cname', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('stage', models.CharField(choices=[('الاولى', 'الاولى'), ('الثانية', 'الثانية'), ('الثالثة', 'الثالثة'), ('الرابعة', 'الرابعة')], max_length=50, verbose_name='المرحلة')),
                ('state', models.CharField(default='مباشرة', max_length=100, verbose_name='حالة الطالب')),
                ('date', models.DateField(verbose_name='تاريخ المباشرة')),
                ('year', models.CharField(max_length=50, verbose_name='العام الدراسي')),
                ('study', models.CharField(choices=[('الصباحية', 'الصباحية'), ('المسائية', 'المسائية')], max_length=20, null=True, verbose_name='الدراسة')),
                ('note', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('img', models.ImageField(blank=True, null=True, upload_to='%y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'مباشرات الطلبة',
            },
        ),
    ]
