# Generated by Django 4.1.2 on 2022-11-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_studentdocument_study_alter_allstudents_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('Dname', models.CharField(max_length=100, verbose_name='القسم')),
                ('Cname', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('content', models.CharField(max_length=200, verbose_name='المحتوى')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%y/%m', verbose_name='اختيار ملف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'البريد',
            },
        ),
    ]
