# Generated by Django 4.1.2 on 2023-03-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0020_senddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdocument",
            name="img_doc",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="stdDoc/%y/",
                verbose_name="صورة الوثيقة",
            ),
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="img_qr",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="stdDoc/%y/",
                verbose_name="صورة الباركود",
            ),
        ),
    ]
