# Generated by Django 4.1.2 on 2024-03-29 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="اسم المقرر الدراسي"),
                ),
                ("description", models.TextField(verbose_name="الوصف")),
                (
                    "credit_hours",
                    models.IntegerField(verbose_name="عدد ساعات الائتمان"),
                ),
            ],
            options={
                "verbose_name": "المقرر الدراسي",
                "verbose_name_plural": "المقررات الدراسية",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="القسم")),
            ],
            options={
                "verbose_name": "القسم",
                "verbose_name_plural": "الأقسام",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preparatory_school_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="معدل المرحلة الاعدادية",
                    ),
                ),
                (
                    "preparatory_study_branch",
                    models.CharField(
                        max_length=200, verbose_name="فرع الدراسة الاعدادية"
                    ),
                ),
                ("sex", models.CharField(max_length=10, verbose_name="الجنس")),
                (
                    "year_of_admission",
                    models.PositiveSmallIntegerField(verbose_name="سنة الالتحاق"),
                ),
                (
                    "school_name",
                    models.CharField(max_length=200, verbose_name="اسم المدرسة"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="رقم الهاتف"),
                ),
                (
                    "parent_phone_number",
                    models.CharField(max_length=15, verbose_name="رقم هاتف ولي الامر"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الالكتروني"),
                ),
                ("section", models.CharField(max_length=100, verbose_name="القسم")),
                (
                    "photograph",
                    models.ImageField(
                        upload_to="student_photos/", verbose_name="الصورة"
                    ),
                ),
                (
                    "student_file",
                    models.FileField(
                        upload_to="student_files/", verbose_name="الملف الطلابي"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "الطالب",
                "verbose_name_plural": "الطلاب",
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.department",
                        verbose_name="القسم",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "الأستاذ",
                "verbose_name_plural": "الأساتذة",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="التاريخ"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="تم القراءة"),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستقبل",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
            ],
            options={
                "verbose_name": "الإشعار",
                "verbose_name_plural": "الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.FloatField(verbose_name="الدرجة")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.course",
                        verbose_name="المقرر الدراسي",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.professor",
                        verbose_name="الأستاذ",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.student",
                        verbose_name="الطالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "الدرجة",
                "verbose_name_plural": "الدرجات",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="تاريخ الامتحان")),
                ("exam_time", models.TimeField(verbose_name="وقت الامتحان")),
                (
                    "room_number",
                    models.CharField(max_length=20, verbose_name="رقم الغرفة"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.course",
                        verbose_name="المقرر الدراسي",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.professor",
                        verbose_name="الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "الامتحان",
                "verbose_name_plural": "الامتحانات",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sis.department",
                verbose_name="القسم",
            ),
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(max_length=20, verbose_name="يوم الأسبوع"),
                ),
                ("time_start", models.TimeField(verbose_name="وقت البدء")),
                ("time_end", models.TimeField(verbose_name="وقت الانتهاء")),
                (
                    "room_number",
                    models.CharField(max_length=20, verbose_name="رقم الغرفة"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.course",
                        verbose_name="المقرر الدراسي",
                    ),
                ),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sis.professor",
                        verbose_name="الأستاذ",
                    ),
                ),
            ],
            options={
                "verbose_name": "جدول الحصص",
                "verbose_name_plural": "جداول الحصص",
            },
        ),
    ]
